# 公告（右侧“公告”卡片）
aside:
  card_announcement: 99@966405.xyz
    enable: true
    content: |
      日常
      

# 顶部大图（你想换右边那条大背景就改它）
index_img: /img/tu1.jpg
default_top_img: /img/tu1.jpg

# 页面底色（不想要花里胡哨就用淡色）
background:
  enable: true
  background: url(/img/tu1.jpg)
  position: center center
  repeat: no-repeat
  size: cover
  attachment: fixed
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <script src="/js/sakura.js"></script>
footer:
  owner:
    enable: true
    since: 2026
  custom_text: "© 2026 why | 记录"
  copyright: false
