# 公告（右侧“公告”卡片）
aside:
  card_announcement:
    enable: true
    content: |
      日常
      

# 顶部大图（你想换右边那条大背景就改它）
index_img: /img/tu1.jpg
default_top_img: /img/tu1.jpg

# 页面底色（不想要花里胡哨就用淡色）
background:
  enable: true
  background: "linear-gradient(135deg,#f7e8ff 0%,#ffe1f0 100%)"
inject:
  head:
  bottom:
    - <script src="/js/sakura.js"></script>
